services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-repo-search-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Application settings
      - NODE_ENV=production
      - PORT=3000
      
      # GitHub API token (optional but recommended)
      # Uncomment and add your token to increase rate limits
      # - GITHUB_TOKEN=your_github_token_here
      
      # Scoring weights (optional, defaults will be used if not set)
      # - SCORE_WEIGHT_STARS=0.4
      # - SCORE_WEIGHT_FORKS=0.3
      # - SCORE_WEIGHT_RECENCY=0.3
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    
    # Resource limits (optional, recommended for production)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Networks
    networks:
      - github-api-network

networks:
  github-api-network:
    driver: bridge

